default:
	cd amd64 && $(MAKE)
	cd arm64 && $(MAKE)
	cd docker_amd64 && $(MAKE)
	cd docker_arm64 && $(MAKE)

clean:
	cd amd64 && $(MAKE) clean
	cd arm64 && $(MAKE) clean
	cd docker_amd64 && $(MAKE) clean
	cd docker_arm64 && $(MAKE) clean